version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --tag my-image:latest \
              --build-arg JAR_FILE=target/my-app.jar \
              -f Dockerfile \
              .
      - run:
          name: Login to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag my-image:latest my-registry/my-image:latest
            docker push my-registry/my-image:latest
