version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11

    working_directory: ~/my-java-app

    steps:
      - checkout

      # Install necessary packages
      - run:
          name: Install Java and Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk-headless maven

      # Verify Java installation
      - run:
          name: Verify Java Installation
          command: java -version

      # Verify Maven installation
      - run:
          name: Verify Maven Installation
          command: mvn -version

      # Build the Java application
      - run: mvn clean install

      # Upload build artifact to S3
      - run:
          name: Upload Build Artifact to S3
          command: |
            aws configure set aws_access_key_id $ACCESSKEY
            aws configure set aws_secret_access_key $SECRETKEY
            aws s3 sync build/ s3://my-test-1-buck --delete
            echo "Build artifact uploaded to S3"

workflows:
  version: 2
  build:
    jobs:
      - build
